### ISSUE TITLE
ActivityMainBinding and FragmentTitleBinding unresolved reference

### ISSUE THREAD

**Issue by stacyjacks** [udacity/andfun-kotlin-android-trivia#9]
I don't know if this only happened to me, but when I tried binding the layout to the TitleFragment, the com.example.android.navigation.databinding.ActivityMainBinding (in MainActivity.kt) and com.example.android.navigation.databinding.FragmentTitleBinding (in TitleFragment) imports were giving me an unresolved reference error and consequently a compilation error.

I fixed them by adding **kapt "com.android.databinding:compiler:3.1.4"** to the app build.gradle file and that seems to have done the trick, but given that I am somewhat of a novice I'm unsure whether it's just a quick fix or it was the right thing to do. Could you please confirm? Thanks.

**Comment by jheske** [comment]
The errors seem to indicate that Android couldn't bind the layout files because there's some kind of binding error.  Debugging data binding errors is notoriously tricky because Android doesn't provide much feedback.  Sometimes you just have to search the build output for "error" and there is usually a line describing the binding error.  

In case there's a version conflict somewhere, try copying the library dependencies from our completed code on the master branch.  That version works without the additional library.

If all else fails, compare your code to our solution.

**Comment by geekyJock8** [comment]
I also encountered this problem while going through this the second lesson(Layouts)!
I fixed it by rebuilding the project after changing to root element to <layout> in the activity_main.xml file.

[Here's the StackOverflow thread from where I got the hint!](https://stackoverflow.com/a/56667368)

**Comment by GrapeJuice787** [comment]
Yeah this is not working for myself either. Very unfortunate, I am going to follow through the videos and not troubleshoot it any further I've wasted hours already.

**Comment by mishkuza** [comment]
> 
> 
> The errors seem to indicate that Android couldn't bind the layout files because there's some kind of binding error. Debugging data binding errors is notoriously tricky because Android doesn't provide much feedback. Sometimes you just have to search the build output for "error" and there is usually a line describing the binding error.
> 
> In case there's a version conflict somewhere, try copying the library dependencies from our completed code on the master branch. That version works without the additional library.
> 
> If all else fails, compare your code to our solution.

Hello jheske,

This issue is still present. I've cloned the project and it occurs on master branch, the latest commit
![s1](https://user-images.githubusercontent.com/34512184/67160955-8bd55480-f35e-11e9-85f3-8b41782a21ac.PNG)
![s2](https://user-images.githubusercontent.com/34512184/67160956-8bd55480-f35e-11e9-8b0a-035bc1e78fd3.PNG)

 for all fragments which use data binding

**Comment by jheske** [comment]
Hi Mishkuza, The master branch of that project does work as far as I know. I no longer work for Udacity, but master was last updated and working 6 months ago. Try selecting "Invalidate Caches / Restart" from the File menu (not sure where it is on Win).

**Comment by mishkuza** [comment]
> 
> 
> Hi Mishkuza, The master branch of that project does work as far as I know. I no longer work for Udacity, but master was last updated and working 6 months ago. Try selecting "Invalidate Caches / Restart" from the File menu (not sure where it is on Win).

@jheske thank you so much! I often forget to try it first and instead go to stackoverflow and dig in there trying loophole solutions ... Cheers to you, even though it's not in your duties anymore to follow here, thank you!

**Comment by mochadwi** [comment]
> Hi Mishkuza, The master branch of that project does work as far as I know. I no longer work for Udacity, but master was last updated and working 6 months ago. Try selecting "Invalidate Caches / Restart" from the File menu (not sure where it is on Win).

The basic and fundamental things to do tends to be forgotten. After Invalidate the caches & restart, the Data Binding works like expected once more.

**Comment by GalenWong** [comment]
I can also confirm that "Invalidate Caches / Restart" fixes the problem.

**Comment by yavinash1413** [comment]
i have done and checked all this hints but still getting error

**Comment by sajib21** [comment]
> i have done and checked all this hints but still getting error

@yavinash1413 did you solve the problem finally?

**Comment by IrshadKasana** [comment]
did you got the solution to this very problem I'm getting the same issue

**Comment by im-ashraf** [comment]
The name is derived from the name of the layout file, that is, activity_main + Binding. Make sure it follows the same pattern

**Comment by houmie** [comment]
I have this problem on a new fresh project. So based on the steps that we have to take
1) I added an blank fragment_policy.xml
2) It also created PolicyFragment.kt for me.
3) Inside ```override fun onCreateView()``` of PolicyFragment.kt I can't instantiate the binding. It's not found. (Despite building and invalidating the project)

Under the generated java files under ```java/com.company.app/databinding``` I can only see ```ActivityMainBindingImpl```

There is nothing about fragment. Have I missed anything? Thank you so much for your help

**Comment by houmie** [comment]
I found the reason. Despite adding fragment through Android Studio it doesn't add <Layout> tag to the fragment view, making it worthless. Until you do it by hand.

**Comment by Doenut999** [comment]
Hi guys, I may have found the resolution to this problem.
You should nest your **_TitleFragment_** layout inside a _layout_ tag, fix up the namespace declarations and create your _data tags_ inside the Fragment Layout. That will fix the type mismatch from ViewBindingUtil to whatever you are using +util. Attaching pictures because my English is horrible. Love from Ghana

https://drive.google.com/file/d/14D1VCtkOumKPDk7pR8mh5cJ06Pe_SLZO/view?usp=sharing
https://drive.google.com/file/d/1r-VO5FpShAx65xwhe0VEF7ZhNe96MCtX/view?usp=sharing
